fix/activate_plugin_skills
```
 14:14:45.286 - skills - mycroft.skills.skill_manager:activate_skill:754 - ERROR - Couldn't activate skill
Traceback (most recent call last):
  File "/home/ovos/.local/lib/python3.10/site-packages/mycroft/skills/skill_manager.py", line 752, in activate_skill
    skill_loader.activate()
  File "/home/ovos/.local/lib/python3.10/site-packages/mycroft/skills/skill_loader.py", line 419, in activate
    self.load()
TypeError: PluginSkillLoader.load() missing 1 required positional argument: 'skill_class'

```